--  Race Seed 
-- Dwarf
INSERT INTO races (race, ability_score_bonus, size, speed, traits, languages, male_name, female_name, clan_or_family_name) VALUES ('Hill Dwarf','+2 Constituion, +1 Wisdom','Medium', 25, 'Darkvision, Dwarven Resilience, Dwarven Combat Training, Stone Cunning, Tool Proficiency, Dwarven Toughness', 'Common, Dwarvish', 'Adrik, Alberich, Baren, Barendd, Brottor, Bruenor, Dain, Darrak, Delg, Eberk, Einkil, Fargrim, Flint, Gardain, Harbek, Kildrak, Morgran, Orsik, Oskar, Rangrim, Rurik, Taklinn, Thoradin, Thorin, Tordek, Traubon, Travok, Ulfgar, Veit, Vondal', 'Amber, Artin, Audhild, Bardryn, Dagnal, Diesa, Eldeth, Falkrunn, Finellen, Gunnloda, Gurdis, Helja, Hlin, Kathra, Kristryd, Ilde, Liftrasa, Mardred, Riswynn, Sannl, Torbera, Torgga, Vistra', 'Balderk, Battlehammer, Brawnanvil, Dankil, Fireforge, Frostbeard, Gorunn, Holderhek, Ironfist, Loderr, Lutgehr, Rumnaheim, Strakeln, Torunn, Ungart');
INSERT INTO races (race, ability_score_bonus, size, speed, traits, languages, male_name, female_name, clan_or_family_name) VALUES ('Mountain Dwarf','+2 Constituion, +2 Strength','Medium', 25, 'Darkvision, Dwarven Resilience, Dwarven Combat Training, Stone Cunning, Tool Proficiency, Dwarven Armor Training','Common, Dwarvish', 'Adrik, Alberich, Baren, Barendd, Brottor, Bruenor, Dain, Darrak, Delg, Eberk, Einkil, Fargrim, Flint, Gardain, Harbek, Kildrak, Morgran, Orsik, Oskar, Rangrim, Rurik, Taklinn, Thoradin, Thorin, Tordek, Traubon, Travok, Ulfgar, Veit, Vondal', 'Amber, Artin, Audhild, Bardryn, Dagnal, Diesa, Eldeth, Falkrunn, Finellen, Gunnloda, Gurdis, Helja, Hlin, Kathra, Kristryd, Ilde, Liftrasa, Mardred, Riswynn, Sannl, Torbera, Torgga, Vistra', 'Balderk, Battlehammer, Brawnanvil, Dankil, Fireforge, Frostbeard, Gorunn, Holderhek, Ironfist, Loderr, Lutgehr, Rumnaheim, Strakeln, Torunn, Ungart');
-- Elf
INSERT INTO races (race, ability_score_bonus, size, speed, traits, languages, male_name, female_name, clan_or_family_name) VALUES ('High Elf','+1 Intelligence, +2 Dexterity','Medium',30,'Darkvision, Keen Senses, Fey Ancestry, Trance, Elf Weapon Training, Cantrip, Extra Language','Common, Elvish','Adran, Aelar, Aramil, Arannis, Aust, Beiro, Berrian, Carric, Enialis, Erdan, Erevan, Galinndan, Hadarai, Heian, Himo, Immeral, Ivellios, Laucian, Mindartis, Paelias, Peren, Quarion, Riardon, Rolen, Soveliss, Thamior, Tharivol, Theren, Varis','Adrie, Althaea, Anastrianna, Andraste, Antinua, Bethrynna, Birel, Caelynn, Drusilia, Enna, Felosial, Ielenia, Jelenneth, Keyleth, Leshanna, Lia, Meriele, Mialee, Naivara, Quelenna, Quillathe, Sariel, Shanairra, Shava, Silaqui, Theirastra, Thia, Vadania, Valanthe, Xanaphia','Amakiir (Gemflower), Amastacia (Starflower), Galanodel (Moonwhisper), Holimion (Diamonddew), Ilphelkiir (Gemblossom), Liadon (Silverfrond), Meliamne (Oakenheel), Nailo (Nightbreeze), Siannodel (Moonbrook), Xiloscient (Goldpetal)');
INSERT INTO races (race, ability_score_bonus, size, speed, traits, languages, male_name, female_name, clan_or_family_name) VALUES ('Wood Elf','+1 Wisdom, +2 Dexterity','Medium',30,'Darkvision, Keen Senses, Fey Ancestry, Trance, Elf Weapon Training, Fleet of Foot, Mask of the Wild','Common, Elvish','Adran, Aelar, Aramil, Arannis, Aust, Beiro, Berrian, Carric, Enialis, Erdan, Erevan, Galinndan, Hadarai, Heian, Himo, Immeral, Ivellios, Laucian, Mindartis, Paelias, Peren, Quarion, Riardon, Rolen, Soveliss, Thamior, Tharivol, Theren, Varis','Adrie, Althaea, Anastrianna, Andraste, Antinua, Bethrynna, Birel, Caelynn, Drusilia, Enna, Felosial, Ielenia, Jelenneth, Keyleth, Leshanna, Lia, Meriele, Mialee, Naivara, Quelenna, Quillathe, Sariel, Shanairra, Shava, Silaqui, Theirastra, Thia, Vadania, Valanthe, Xanaphia','Amakiir (Gemflower), Amastacia (Starflower), Galanodel (Moonwhisper), Holimion (Diamonddew), Ilphelkiir (Gemblossom), Liadon (Silverfrond), Meliamne (Oakenheel), Nailo (Nightbreeze), Siannodel (Moonbrook), Xiloscient (Goldpetal)');
INSERT INTO races (race, ability_score_bonus, size, speed, traits, languages, male_name, female_name, clan_or_family_name) VALUES ('Dark Elf (Drow)','+1 Charisma, +2 Dexterity','Medium',30,'Superior Darkvision, Keen Senses, Fey Ancestry, Trance, Sunlight Sensitivity, Drow Magic, Drow Weapon Training','Common, Elvish','Adran, Aelar, Aramil, Arannis, Aust, Beiro, Berrian, Carric, Enialis, Erdan, Erevan, Galinndan, Hadarai, Heian, Himo, Immeral, Ivellios, Laucian, Mindartis, Paelias, Peren, Quarion, Riardon, Rolen, Soveliss, Thamior, Tharivol, Theren, Varis','Adrie, Althaea, Anastrianna, Andraste, Antinua, Bethrynna, Birel, Caelynn, Drusilia, Enna, Felosial, Ielenia, Jelenneth, Keyleth, Leshanna, Lia, Meriele, Mialee, Naivara, Quelenna, Quillathe, Sariel, Shanairra, Shava, Silaqui, Theirastra, Thia, Vadania, Valanthe, Xanaphia','Amakiir (Gemflower), Amastacia (Starflower), Galanodel (Moonwhisper), Holimion (Diamonddew), Ilphelkiir (Gemblossom), Liadon (Silverfrond), Meliamne (Oakenheel), Nailo (Nightbreeze), Siannodel (Moonbrook), Xiloscient (Goldpetal)');
-- Halfling
INSERT INTO races (race, ability_score_bonus, size, speed, traits, languages, male_name, female_name, clan_or_family_name) VALUES ('Lightfoot Halfling','+1 Charisma, +2 Dexterity','Small',25,'Lucky, Brave, Halfling Nimbleness, Naturally Stealthy','Common, Halfling','Alton, Cade, Corrin, Eldon, Errich, Finnan, Garret, Lindal, Lyle, Merric, Milo, Osborn, Perrin, Reed, Roscoe, Wellby',' Andry, Bree, Callie, Cora, Euphemia, Jillian, Kithri, Lavinia, Lidda, Merla, Nedda, Paela, Portia, Seraphina, Shaena, Trym, Vani, Verna','Brushgather, Goodbarrel, Greenbottle, High-hill, Hilltopple, Leagallow,Tealeaf, Thorngage, Tosscobble, Underbough');
INSERT INTO races (race, ability_score_bonus, size, speed, traits, languages, male_name, female_name, clan_or_family_name) VALUES ('Stout Halfling','+1 Constituion, +2 Dexterity','Small',25,'Lucky, Brave, Halfling Nimbleness, Stout Resilience','Common, Halfling','Alton, Cade, Corrin, Eldon, Errich, Finnan, Garret, Lindal, Lyle, Merric, Milo, Osborn, Perrin, Reed, Roscoe, Wellby',' Andry, Bree, Callie, Cora, Euphemia, Jillian, Kithri, Lavinia, Lidda, Merla, Nedda, Paela, Portia, Seraphina, Shaena, Trym, Vani, Verna','Brushgather, Goodbarrel, Greenbottle, High-hill, Hilltopple, Leagallow,Tealeaf, Thorngage, Tosscobble, Underbough');
-- Human
INSERT INTO races (race, ability_score_bonus, size, speed, traits, languages, male_name, female_name, clan_or_family_name) VALUES ('Human','+1 Strength, +1 Dexterity, +1 Constituion, +1 Intelligence, +1 Wisdom, +1 Charisma','Medium',30,'N/A','Common, 1 Extra Language','Bor, Fodel, Glar, Grigor, Igan, Ivor, Kosef, Mival, Orel, Pavel, Sergor, Ander, Blath, Bran, Frath, Geth, Lander, Luth, Malcer, Stor, Taman, UrthAoth, Bareris, Ehput-ki, Kethtoth, Mumed, Ramas, So-Kehur, Thazar-De, Urhur, Borivik, Faurgar, Jandar, Kanithar, Madislak, Ralmevik, Shaumar, Vladislak, An, Chen, Chi, Fai, Jiang, Jun, Lian, Long, Meng, On, Shan, Shui, Wen, Anton, Diero, Marcon, Pieron, Rimardo, Romero, Salazar, Umbero','Alethra, Kara, Katernin, Mara, Natali, Olma, Tana, Zora, Amafrey, Betha, Cefrey, Kethra, Mara, Olga, Silifrey, Westra, Arizima, Chathi, Nephis, Nulara, Murithi, Sefris, Thola, Umara, Zolis, Fyevarra, Hulmarra, Immith, Imzel, Navarra, Shevarra, Tammith, Yuldra, Bai, Chao, Jia, Lei, Mei, Qiao, Shui, Tai, Balama, Dona, Faila, Jalana, Luisa, Marta, Quara, Selise, Vonda','Berks, Chernin, Dotsk, Kulenov, Marsk, Nemetsk, Shemov, Starag, Brightwood, Helder, Hornraven, Lackman, Stormwind, Windrivver, Ankhalab, Fezim, Hahpet, Nathandem, Sepret, Uuthraky, Chergoba, Dyernina, Iltazyara, Murnyethara, Stayanoga, Ulmokina, Chien, Huang, Kao, Kung, Lao, Ling, Mei, Pin, Shin, Sum, Tan, Wan, Agosto, Astorio, Calabra, Domine, Falone, Marivaldi, Pisacar, Ramondo');
-- Dragonborn
INSERT INTO races (race, ability_score_bonus, size, speed, traits, languages, male_name, female_name, clan_or_family_name) VALUES ('Dragonborn','+2 Strength, +1 Charisma','Medium',30,'Draconic Ancestry, Breath Weapon, Damage Resistance','Common, Draconic','Arjhan, Balasar, Bharash, Donaar, Ghesh, Heskan, Kriv, Medrash, Mehen, Nadarr, Pandjed, Patrin, Rhogar, Shamash, Shedinn, Tarhun, Torinn','Akra, Biri, Daar, Farideh, Harann, Havilar, Jheri, Kava, Korinn, Mishann, Nala, Perra, Raiann, Sora, Surina, Thava, Uadjit','Clethtinthiallor, Daardendrian, Delmirev, Drachedandion, Fenkenkabradon, Kepeshkmolik, Kerrhylon, Kimbatuul, Linxakasendalor, Myastan, Nemmonis, Norixius, Ophinshtalajiir, Prexijandilin, Shestendeliath, Turnuroth, Verthisathurgiesh, Yarjerit');
-- Gnome
INSERT INTO races (race, ability_score_bonus, size, speed, traits, languages, male_name, female_name, clan_or_family_name) VALUES ('Forest Gnome','+2 Intelligence, +1 Dexterity','Small',25,'Darkvision, Gnome Cunning, Natural Illusionist, Speak with Small Beasts','Common, Gnomish','Alston, Alvyn, Boddynock, Brocc, Burgell, Dimble, Eldon, Erky, Fonkin, Frug, Gerbo, Gimble, Glim, Jebeddo, Kellen, Namfoodle, Orryn, Roondar, Seebo, Sindri, Warryn, Wrenn, Zook','Bimpnottin, Breena, Caramip, Carlin, Donella, Duvamil, Ella, Ellyjobell, Ellywick, Lilli, Loopmottin, Lorilla, Mardnab, Nissa, Nyx, Oda, Orla, Roywyn, Shamil, Tana, Waywocket, Zanna','Beren, Daergel, Folkor, Garrick, Nackle, Murnig, Ningel, Raulnor, Scheppen, Timbers, Turen');
INSERT INTO races (race, ability_score_bonus, size, speed, traits, languages, male_name, female_name, clan_or_family_name) VALUES ('Rock Gnome','+2 Intelligence, +1 Constituion','Small',25,'Darkvision, Gnome Cunning, Artificers Lore, Tinker','Common, Gnomish','Alston, Alvyn, Boddynock, Brocc, Burgell, Dimble, Eldon, Erky, Fonkin, Frug, Gerbo, Gimble, Glim, Jebeddo, Kellen, Namfoodle, Orryn, Roondar, Seebo, Sindri, Warryn, Wrenn, Zook','Bimpnottin, Breena, Caramip, Carlin, Donella, Duvamil, Ella, Ellyjobell, Ellywick, Lilli, Loopmottin, Lorilla, Mardnab, Nissa, Nyx, Oda, Orla, Roywyn, Shamil, Tana, Waywocket, Zanna','Beren, Daergel, Folkor, Garrick, Nackle, Murnig, Ningel, Raulnor, Scheppen, Timbers, Turen');
-- Half-Elf
INSERT INTO races (race, ability_score_bonus, size, speed, traits, languages, male_name, female_name, clan_or_family_name) VALUES ('Half-Elf','+2 Charisma, +1 Any 2 Abilities','Medium',30,'Darkvision, Fey Ancestry, Skill Versatility','Common, Elvish,1 Extra Language','Adran, Aelar, Aramil, Arannis, Aust, Beiro, Berrian, Carric, Enialis, Erdan, Erevan, Galinndan, Hadarai, Heian, Himo, Immeral, Ivellios, Laucian, Mindartis, Paelias, Peren, Quarion, Riardon, Rolen, Soveliss, Thamior, Tharivol, Theren, Varis, Bor, Fodel, Glar, Grigor, Igan, Ivor, Kosef, Mival, Orel, Pavel, Sergor, Ander, Blath, Bran, Frath, Geth, Lander, Luth, Malcer, Stor, Taman, UrthAoth, Bareris, Ehput-ki, Kethtoth, Mumed, Ramas, So-Kehur, Thazar-De, Urhur, Borivik, Faurgar, Jandar, Kanithar, Madislak, Ralmevik, Shaumar, Vladislak, An, Chen, Chi, Fai, Jiang, Jun, Lian, Long, Meng, On, Shan, Shui, Wen, Anton, Diero, Marcon, Pieron, Rimardo, Romero, Salazar, Umbero','Adrie, Althaea, Anastrianna, Andraste, Antinua, Bethrynna, Birel, Caelynn, Drusilia, Enna, Felosial, Ielenia, Jelenneth, Keyleth, Leshanna, Lia, Meriele, Mialee, Naivara, Quelenna, Quillathe, Sariel, Shanairra, Shava, Silaqui, Theirastra, Thia, Vadania, Valanthe, Xanaphia, Alethra, Kara, Katernin, Mara, Natali, Olma, Tana, Zora, Amafrey, Betha, Cefrey, Kethra, Mara, Olga, Silifrey, Westra, Arizima, Chathi, Nephis, Nulara, Murithi, Sefris, Thola, Umara, Zolis, Fyevarra, Hulmarra, Immith, Imzel, Navarra, Shevarra, Tammith, Yuldra, Bai, Chao, Jia, Lei, Mei, Qiao, Shui, Tai, Balama, Dona, Faila, Jalana, Luisa, Marta, Quara, Selise, Vonda','Berks, Chernin, Dotsk, Kulenov, Marsk, Nemetsk, Shemov, Starag, Brightwood, Helder, Hornraven, Lackman, Stormwind, Windrivver, Ankhalab, Fezim, Hahpet, Nathandem, Sepret, Uuthraky, Chergoba, Dyernina, Iltazyara, Murnyethara, Stayanoga, Ulmokina, Chien, Huang, Kao, Kung, Lao, Ling, Mei, Pin, Shin, Sum, Tan, Wan, Agosto, Astorio, Calabra, Domine, Falone, Marivaldi, Pisacar, Ramondo, Amakiir (Gemflower), Amastacia (Starflower), Galanodel (Moonwhisper), Holimion (Diamonddew), Ilphelkiir (Gemblossom), Liadon (Silverfrond), Meliamne (Oakenheel), Nailo (Nightbreeze), Siannodel (Moonbrook), Xiloscient (Goldpetal)');
-- Half-Orc
INSERT INTO races (race, ability_score_bonus, size, speed, traits, languages, male_name, female_name, clan_or_family_name) VALUES ('Half-Orc','+2 Strength, +1 Constitution','Medium',30,'Darkvision, Menacing, Relentless Endurance, Savage Attacks','Common, Orc','Dench,Feng,Gell,Henk,Holg,Imsh,Keth,Krusk,Mhurren,Ront,Shump,Thokk','Baggi,Emen,Engong,Kansif,Myev,Neega,Ovak,Ownka,Shautha,Sutha,Vola,Volen,Yevelda','Berks,Chernin,Dotsk,Kulenov,Marsk,Nemetsk,Shemov,Starag,Brightwood,Helder,Hornraven,Lackman,Stormwind,Windrivver,Ankhalab,Fezim,Hahpet,Nathandem,Sepret,Uuthraky,Chergoba,Dyernina,Iltazyara,Murnyethara,Stayanoga,Ulmokina,Chien,Huang,Kao,Kung,Lao,Ling,Mei,Pin,Shin,Sum,Tan,Wan,Agosto,Astorio,Calabra,Domine,Falone,Marivaldi,Pisacar,Ramondo,Cavernshred,Spineshred,Rantsnapper,Rantshade,Dreadgouger,Dreadbasher,Nightbane,Wormbane,Deathgouger,Blacksnapper');
-- Tiefling
INSERT INTO races (race, ability_score_bonus, size, speed, traits, languages, male_name, female_name, clan_or_family_name) VALUES ('Tiefling','+1 Intelligence, +2 Charisma','Medium',30,'Darkvision, Hellish Resistance, Infernal Legacy','Common, Infernal','Akmenos, Amnon, Barakas, Damakos, Ekemon, Iados, Kairon, Leucis, Melech, Mordai, Morthos, Pelaios, Skamos, Therai','Akta, Anakis, Bryseis, Criella, Damaia, Ea, Kallista, Lerissa, Makaria, Nemeia, Orianna, Phelaia, Rieta','Art, Carrion, Chant, Creed, Despair, Excellence, Fear, Glory, Hope, Ideal, Music, Nowhere, Open, Poetry, Quest, Random, Reverence, Sorrow, Temerity, Torment, Weary');

-- Class Seed
-- Note: For all classes, Constitution modifiers needs to be factored into starting health
-- Barbarian
INSERT INTO classes (class, hit_dice, hp, armor_proficiencies, weapon_proficiencies, tool_proficiencies, saving_throws, skills, choose_skills, starting_equipment, features, cantrips,spells_known_or_prepared, spell_slots) VALUES ('Barbarian','d12',12,'Light armor, Medium armor, Shields','Simple weapon, Martial weapons','None','Strength, Constitution','Animal Handling, Athletics, Intimidation, Nature, Perception, Survival',2,'Greataxe, Any Martial Melee Weapon;Two Handaxes, Any Simple Weapon;An explorers pack and Four javelins','Rage, Unarmored Defense',0,0,0);
-- Bard
INSERT INTO classes (class, hit_dice, hp, armor_proficiencies, weapon_proficiencies, tool_proficiencies, saving_throws, skills, choose_skills, starting_equipment, features, cantrips, spells_known_or_prepared,spell_slots) VALUES ('Bard','d8',8,'Light armor','Simple weapons, Hand crossbows, Longswords, Rapiers, Shortswords','Three musical instruments of your choice','Dexterity, Charisma','Acrobatics, Animal Handling, Arcana, Athletics, Deception, History, Insight, Intimidation, Investigation, Medicin, Nature, Perception, Performance, Persuasion, Religion, Sleight of Hand, Stealth, Survival',3,'Rapier, Longsword, Any simple weapon;A diplomats pack, An entertainers pack;Any musical instrument;Leather armor and a dagger','Spellcasting, Bardic Inspiration(d6)',3,4,2);
-- Cleric
-- Note: spells, spells prepared formula is lvl (1) + Wisdom modifier
INSERT INTO classes (class, hit_dice, hp, armor_proficiencies, weapon_proficiencies, tool_proficiencies, saving_throws, skills, choose_skills, starting_equipment, features, cantrips, spells_known_or_prepared,spell_slots) VALUES ('Cleric','d8',8,'Light armor, Medium armor, Shields','All simple weapons','None','Wisdom, Charisma','History, Insight, Medicine, Persuasion, Religion',2,'Mace, Warhammer;Scale mail, Leather armor, Chain mail;Light crossbow with 20 bolts, Any simple weapon;A priests pack, An explorers pack;A shield and a holy symbol','Spellcasting, Divine Domain',3,1,2);
-- Druid
-- Note: spells, spells prepared formula is lvl (1) + Wisdom modifier
INSERT INTO classes (class, hit_dice, hp, armor_proficiencies, weapon_proficiencies, tool_proficiencies, saving_throws, skills, choose_skills, starting_equipment, features, cantrips, spells_known_or_prepared,spell_slots) VALUES ('Druid','d8',8,'Light armor (non-metal), Medium armor (non-metal), Shields (non-metal)','Clubs, Daggers, Darts, Javelins, Maces, Quarterstaffs, Scimitars, Sickles, Slings, Spears','Herbalism kit','Intelligence, Wisdom','Arcana, Animal Handling, Insight, Medicine, Nature, Perception, Religion, Survival',2,'Wooden shield, Any simple weapon;Scimitar, Any simple melee weapon;Leather armor and an explorers pack and druidic focus','Druidic, Spellcasting',2,1,2);
--Fighter
INSERT INTO classes (class, hit_dice, hp, armor_proficiencies, weapon_proficiencies, tool_proficiencies, saving_throws, skills, choose_skills, starting_equipment, features, cantrips, spells_known_or_prepared,spell_slots) VALUES ('Fighter','d10',10,'All armors, Shields','Simple weapons, Martial weapons','None','Strength, Constitution','Acrobatics, Animal Handling, Athletics, History, Insight, Intimidation, Perception, Survival',2,'Chain mail, Leather armor and Longbow with 20 arrows;A martial weapon and shield, Two martial weapons;Light crossbow with 20 bolts, Two handaxes;Dungeoneers pack, Explorers pack','Fighting Style, Second Wind',0,0,0);
--Monk
INSERT INTO classes (class, hit_dice, hp, armor_proficiencies, weapon_proficiencies, tool_proficiencies, saving_throws, skills, choose_skills, starting_equipment, features, cantrips, spells_known_or_prepared,spell_slots) VALUES ('Monk','d8',8,'None','Simple weapons, Shortswords','One artisan tool or one instrument','Strength, Dexterity','Acrobatics, Athletics, History, Insight, Religion, Stealth',2,'Shortsword, Any simple weapon;Dungeoneers pack, Explorers pack;10 darts','Unarmored Defense, Martial Arts',0,0,0);
-- Paladin
INSERT INTO classes (class, hit_dice, hp, armor_proficiencies, weapon_proficiencies, tool_proficiencies, saving_throws, skills, choose_skills, starting_equipment, features, cantrips, spells_known_or_prepared,spell_slots) VALUES ('Paladin','d10',10,'All armors, Shield','Simple weapons, Martial weapons','None','Wisdom, Charisma','Athletics, Insight, Intimidation, Medicine, Persuasion, Religion',2,'A martial weapon and shield, Two martial weapons;Five javelins, Any simple melee weapon;A priests pack, An explorers pack;Chain mail and a holy symbol','Divine Sense, Lay on Hands',0,0,0);
-- Ranger
INSERT INTO classes (class, hit_dice, hp, armor_proficiencies, weapon_proficiencies, tool_proficiencies, saving_throws, skills, choose_skills, starting_equipment, features, cantrips, spells_known_or_prepared,spell_slots) VALUES ('Ranger','d10',10,'Light armor, Medium armor, Shields','Simple weapons, Martial Weapons','None','Strength, Dexterity','Animal Handling, Athletics, Insight, Investigation, Nature, Perception, Stealth, Survival',3,'Scale mail, Leather armor;Two shortswords, Two simple melee weapons;A dungeoneers pack, An explorers pack;Longbow and a quiver of 20 arrows','Favored Enemy, Natural Explorer',0,0,0);
-- Rogue
INSERT INTO classes (class, hit_dice, hp, armor_proficiencies, weapon_proficiencies, tool_proficiencies, saving_throws, skills, choose_skills, starting_equipment, features, cantrips, spells_known_or_prepared,spell_slots) VALUES ('Rogue','d8',8,'Light Armor','Simple weapons, Hand crossbows, Longswords, Rapiers, Shortswords','Thieves tools','Dexterity, Intelligence','Acrobatics, Athletics, Deception, Insight, Intimidation, Investigation, Perception, Performance, Persuasion, Sleight of Hand, Stealth',4,'Rapier, Shortsword;Shortbow and 20 arrows, Shortsword;Burglars pack, Dungeoneers Pack, Explorers Pack;Leather armor and two daggers and thieves tools','Expertise, Sneak Attack, Thieves Cant',0,0,0);
-- Sorcerer
INSERT INTO classes (class, hit_dice, hp, armor_proficiencies, weapon_proficiencies, tool_proficiencies, saving_throws, skills, choose_skills, starting_equipment, features, cantrips, spells_known_or_prepared,spell_slots) VALUES ('Sorcerer','d6',6,'None','Daggers, Darts, Slings, Quarterstaffs, Light crossbows','None','Constitution, Charisma','Arcana, Deception, Insight, Intimidation, Persuasion, Religion',2,'Light crossbow and 20 bolts, Any simple weapon;Component pouch, Arcane focus;Dungeoneers pack, Explorers pack;Two daggers','Spellcasting, Sorcerous Origin',4,2,2);
--Warlock
INSERT INTO classes (class, hit_dice, hp, armor_proficiencies, weapon_proficiencies, tool_proficiencies, saving_throws, skills, choose_skills, starting_equipment, features, cantrips, spells_known_or_prepared,spell_slots) VALUES ('Warlock','d8',8,'Light armor','Simple weapons','None','Wisdom, Charisma','Arcana, Deception, History, Intimidation, Investigation, Nature, Religion',2,'Light crossbow and 20 bolts, Any simple weapon;Component pouch, Arcane focus;Scholars pack, Dungeoneers pack;Leather armor and two daggers and any simple weapon','Otherwordly Patron, Pact Magic',2,2,1);
--Wizard
INSERT INTO classes (class, hit_dice, hp, armor_proficiencies, weapon_proficiencies, tool_proficiencies, saving_throws, skills, choose_skills, starting_equipment, features, cantrips, spells_known_or_prepared,spell_slots) VALUES ('Wizard','d6',6,'None','Daggers, Darts, Slings, Quarterstaffs, Light crowssbows','None','Intelligence, Wisdom','Arcana, History, Insight, Investiation, Medicine, Religion',2,'Quarterstaff, Dagger;Component pouch, Arcane focus;Scholars pack, Explorers pack;A spellbook','Spellcasting, Arcane Recovery',3,6,2);
-- Background Seed